apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"create-deployments"},"rules":[{"apiGroups":["*"],"resources":["deployments","pods/*","services","secrets","networkpolicies.networking.k8s.io","pods"],"verbs":["get","list","watch","create","update","patch","apply"]}]}
  creationTimestamp: "2023-04-27T00:56:18Z"
  name: create-deployments
  resourceVersion: "786186"
  uid: 2135dc55-0792-41e4-9295-f02bf957a226
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - pods/*
  - services
  - secrets
  - networkpolicies.networking.k8s.io
  - pods
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - apply
