apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: demo
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: api-demo
        image: 468899338760.dkr.ecr.us-east-1.amazonaws.com/pocjlondonos:master.20230502.1
        resources:
           limits:
             memory: 200Mi
           requests:
             cpu: 100m
             memory: 200Mi
        ports:
        - containerPort: 8080
